name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Look for broken links
        uses: peter-evans/link-checker@v1.2.2
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "."
          arguments: --allow-missing-href
